## 1. 张量的数据类型

In [2]:
## 导入需要的库
import torch

In [4]:
## 获取张量的数据类型
torch.tensor([1.2, 3.4]).dtype

torch.float32

In [8]:
## 张量默认的数据类型 设置调整
torch.set_default_tensor_type(torch.DoubleTensor)
torch.tensor([1.2, 3.4]).dtype

torch.float64

In [9]:
a = torch.tensor([1.2, 3.4])
print("a.dtype", a.dtype)
print("a.long()", a.long().dtype)
print("a.int()", a.int().dtype)
print("a.float()", a.float().dtype)

a.dtype torch.float64
a.long() torch.int64
a.int() torch.int32
a.float() torch.float32


In [10]:
torch.set_default_tensor_type(torch.FloatTensor)
torch.tensor([1.2, 3.4]).dtype

torch.float32

In [12]:
torch.get_default_dtype()

torch.float32

## 2. 生成张量

### 2.1 基本方法

In [15]:
A = torch.tensor([[1.0, 1.0], [2, 2]])
A

tensor([[1., 1.],
        [2., 2.]])

In [16]:
A.shape

torch.Size([2, 2])

In [17]:
A.size()

torch.Size([2, 2])

In [ ]:
## 计算张量中所有元素的个数
A.numel()

4

In [27]:
## 指定张量的数据类型和是否要计算梯度
B = torch.tensor((1,2,3), dtype=torch.float32, requires_grad=True)
B

tensor([1., 2., 3.], requires_grad=True)

In [ ]:
## 因为张量B可计算梯度，所以可以计算 sum(B^2)的梯度
y = B.pow(2).sum()
y.backward()
B.grad

tensor([2., 4., 6.])

In [ ]:
# Only Tensors of floating point and complex dtype can require gradients
# B = torch.tensor((1,2,3), dtype=torch.int32, requires_grad=True) 

RuntimeError: Only Tensors of floating point and complex dtype can require gradients

In [30]:
C = torch.Tensor([1,2,3,4])
C

tensor([1., 2., 3., 4.])

In [32]:
D = torch.Tensor(2,3)
D

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [33]:
torch.ones_like(D)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [34]:
torch.zeros_like(D)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [35]:
torch.rand_like(D)

tensor([[0.2408, 0.3624, 0.7968],
        [0.2176, 0.9197, 0.6323]])

In [36]:
## 创建一个类型相似但尺寸不同的张量
E = [[1,2],[3,4]]
E = D.new_tensor(E)
print("D.dtype", D.dtype)
print("E.dtype", E.dtype)
E

D.dtype torch.float32
E.dtype torch.float32


tensor([[1., 2.],
        [3., 4.]])

In [42]:
D.new_full((3,3), fill_value=1)
D.new_zeros((3,3))
D.new_empty((3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [43]:
## 利用 numpy 数组生成张量
import numpy as np
F = np.ones((3,3))
Ftensor = torch.as_tensor(F)
Ftensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [44]:
Ftensor = torch.from_numpy(F)
Ftensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [45]:
Ftensor.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 2.2 随机生成张量

In [47]:
## 指定均值和标准差生成随机数
torch.manual_seed(123)
A = torch.normal(mean = 0.0, std =torch.tensor(1.0))
A

tensor(-0.1115)

In [49]:
torch.manual_seed(123)
A = torch.normal(mean = 0.0, std =torch.arange(1, 5.0))
A

tensor([-0.1115,  0.2407, -1.1089, -0.9617])

In [50]:
torch.manual_seed(123)
A = torch.normal(mean = torch.arange(1, 5.0), std =torch.arange(1, 5.0))
A

tensor([0.8885, 2.2407, 1.8911, 3.0383])

In [ ]:
torch.manual_seed(123)
B = torch.rand(3, 4)
B

tensor([[0.2961, 0.5166, 0.2517, 0.6886],
        [0.0740, 0.8665, 0.1366, 0.1025],
        [0.1841, 0.7264, 0.3153, 0.6871]])

In [52]:
torch.manual_seed(123)
C = torch.ones(2,3)
D = torch.rand_like(C)
D

tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665]])

In [53]:
torch.manual_seed(123)
torch.randperm(10)

tensor([2, 0, 8, 1, 3, 7, 4, 9, 5, 6])

### 2.3 其他生成张量的函数

In [55]:
torch.arange(start=0, end=10, step=2)

tensor([0, 2, 4, 6, 8])

In [ ]:
## 等间格的点
torch.linspace(start=1, end=10, steps = 5)

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

In [ ]:
## 对数间隔的点
torch.logspace(start=0.1, end=1.0, steps=5)

tensor([ 1.2589,  2.1135,  3.5481,  5.9566, 10.0000])

In [58]:
10 ** (torch.linspace(start=0.1, end=1, steps = 5))

tensor([ 1.2589,  2.1135,  3.5481,  5.9566, 10.0000])

In [63]:
torch.zeros(3,3)
torch.ones(3,3)
torch.eye(3)
torch.empty(3,3)
torch.full((3,3), fill_value=0.25)

tensor([[0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500]])

## 3. 张量的操作

### 3.1 改变张量的尺寸

In [6]:
A = torch.arange(12.0)
A = A.reshape(3, 4)
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [7]:
torch.reshape(input=A, shape=(2, -1))

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])

In [9]:
A.resize_(2,6)
A

tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])

In [ ]:
## 删除多余的
B = torch.arange(10.0, 19.0).reshape(3,3)
A.resize_as_(B)

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [ ]:
## torch.unsqueeze 在指定维度上为张量增加一个维度（大小为 1）。
A = torch.arange(12.0).reshape(2,6)
B = torch.unsqueeze(A, dim = 0) # dim=0, 表示在第 0 维（最外层）增加一个维度。
B.shape

torch.Size([1, 2, 6])

In [ ]:
C = B.unsqueeze(dim=3)
print("C.shape", C.shape)
D = torch.squeeze(C) # 移除所有维度为1的维度
print("D.shape", D.shape)
E = torch.squeeze(C, dim=0)# 移除指定dim层 维度为1的维度
print("E.shape", E.shape)

C.shape torch.Size([1, 2, 6, 1])
D.shape torch.Size([2, 6])
E.shape torch.Size([2, 6, 1])


In [ ]:
# expand方法拓展张量
A = torch.arange(3)
B = A.expand(3, -1)
B

tensor([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]])

In [28]:
## 使用 expand_as 方法拓展张量
C = torch.arange(6).reshape(2,3)
B = A.expand_as(C)
B

tensor([[0, 1, 2],
        [0, 1, 2]])

In [ ]:
print(B)
print(B.shape)
D = B.repeat(1,2,2) 
# 第 0 维重复 1 次 
# 第 1 维重复 2 次
# 第 2 维重复 2 次
print(D)
print(D.shape)

tensor([[0, 1, 2],
        [0, 1, 2]])
torch.Size([2, 3])
tensor([[[0, 1, 2, 0, 1, 2],
         [0, 1, 2, 0, 1, 2],
         [0, 1, 2, 0, 1, 2],
         [0, 1, 2, 0, 1, 2]]])
torch.Size([1, 4, 6])


### 3.2 获取张量中的元素

In [32]:
A = torch.arange(12).reshape(1,3,4)
A

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]])

In [33]:
A[0]

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
## 获取第0维度下的矩阵前两行元素
A[0, 0:2,:]

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])

In [37]:
# 获取0维度下的矩阵， 最后一行的，-4到-1的列
A[0,-1,-4:-1]

tensor([ 8,  9, 10])

In [ ]:
# 根据条件筛选
B= -A
torch.where(A>5, A, B)  # where condition if A else B

tensor([[[ 0, -1, -2, -3],
         [-4, -5,  6,  7],
         [ 8,  9, 10, 11]]])

In [ ]:
# 获取A中大于5的元素
A[A>5]

tensor([ 6,  7,  8,  9, 10, 11])

In [42]:
# 获取其中的 0维度 / 第二行 / 第三列
print(A)
A[0,2,3]

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]])


tensor(11)

In [43]:
## 获取矩阵张量的下三角部分
torch.tril(A, diagonal=0, )

tensor([[[ 0,  0,  0,  0],
         [ 4,  5,  0,  0],
         [ 8,  9, 10,  0]]])

In [44]:
# diagonal 参数控制考虑对角线
torch.tril(A, diagonal=1)

tensor([[[ 0,  1,  0,  0],
         [ 4,  5,  6,  0],
         [ 8,  9, 10, 11]]])

In [45]:
# diagonal 上三角部分
torch.triu(A, diagonal=0)

tensor([[[ 0,  1,  2,  3],
         [ 0,  5,  6,  7],
         [ 0,  0, 10, 11]]])

In [46]:
C = A.reshape(3,4)
print(C)
print(torch.diag(C, diagonal=0))
print(torch.diag(C, diagonal=1))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([ 0,  5, 10])
tensor([ 1,  6, 11])


In [ ]:
# 提供对角线元素生成矩阵张量
torch.diag(torch.tensor([1,2,3]))

tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

### 3.3 拼接和拆分

In [ ]:
A = torch.arange(6.0).reshape(2,3)
B = torch.linspace(0,10,6).reshape(2,3)
#  在0维度拼接张量
C = torch.cat((A,B), dim=0)
C

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 0.,  2.,  4.],
        [ 6.,  8., 10.]])

In [49]:
D = torch.cat((A,B), dim=1)
D

tensor([[ 0.,  1.,  2.,  0.,  2.,  4.],
        [ 3.,  4.,  5.,  6.,  8., 10.]])

In [50]:
E = torch.cat((A[:,1:2], A, B), dim=1)
E

tensor([[ 1.,  0.,  1.,  2.,  0.,  2.,  4.],
        [ 4.,  3.,  4.,  5.,  6.,  8., 10.]])

In [ ]:
F = torch.stack((A,B), dim=0)
print(F)
print(F.shape)
# 2个2*3的矩阵组合在一起

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]])
torch.Size([2, 2, 3])


In [ ]:
G = torch.stack((A,B),dim=2)
print(G)
print(G.shape)
# 2个3*2的矩阵组合在一起

tensor([[[ 0.,  0.],
         [ 1.,  2.],
         [ 2.,  4.]],

        [[ 3.,  6.],
         [ 4.,  8.],
         [ 5., 10.]]])
torch.Size([2, 3, 2])


In [ ]:
torch.chunk(E, 2,dim=0)

(tensor([[1., 0., 1., 2., 0., 2., 4.]]),
 tensor([[ 4.,  3.,  4.,  5.,  6.,  8., 10.]]))

In [56]:
print(D)
D1, D2 = torch.chunk(D, 2, dim=1)
print(D1)
print(D2)

tensor([[ 0.,  1.,  2.,  0.,  2.,  4.],
        [ 3.,  4.,  5.,  6.,  8., 10.]])
tensor([[0., 1., 2.],
        [3., 4., 5.]])
tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])


In [57]:
print(E)
E1, E2, E3 = torch.chunk(E, 3 ,dim=1)
print(E1)
print(E2)
print(E3)

tensor([[ 1.,  0.,  1.,  2.,  0.,  2.,  4.],
        [ 4.,  3.,  4.,  5.,  6.,  8., 10.]])
tensor([[1., 0., 1.],
        [4., 3., 4.]])
tensor([[2., 0., 2.],
        [5., 6., 8.]])
tensor([[ 4.],
        [10.]])


In [58]:
print(D)
D1,D2,D3 =torch.split(D, [1,2,3], dim=1)
print(D1)
print(D2)
print(D3)

tensor([[ 0.,  1.,  2.,  0.,  2.,  4.],
        [ 3.,  4.,  5.,  6.,  8., 10.]])
tensor([[0.],
        [3.]])
tensor([[1., 2.],
        [4., 5.]])
tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])


## 4. 张量计算

### 4.1 比较大小

In [ ]:
A = torch.tensor([10.0])
B = torch.tensor([10.1])
print(torch.allclose(A, B, rtol=1e-05,atol=1e-08, equal_nan=False))
print(torch.allclose(A, B, rtol=0.1,atol=0.01, equal_nan=False))

False
True


In [ ]:
A = torch.tensor(float("nan"))
print(torch.allclose(A, A, equal_nan=False))
print(torch.allclose(A, A, equal_nan=True))

False
True


In [ ]:
# 计算元素是否相等
A = torch.tensor([1,2,3,4,5,6])
B = torch.arange(1,7)
C = torch.unsqueeze(B, dim=0)
print(torch.eq(A, B))
print(torch.eq(A, C))


tensor([True, True, True, True, True, True])
tensor([[True, True, True, True, True, True]])


In [ ]:
# 判断两个张量是否具有相同的尺寸和元素
print(torch.equal(A,B))
print(torch.equal(A,C))

True
False


In [ ]:
# 逐元素比较大于等于
print(torch.ge(A,B))
print(torch.ge(A,C))

tensor([True, True, True, True, True, True])
tensor([[True, True, True, True, True, True]])


In [67]:
# 逐元素比较大于
print(torch.gt(A,B))
print(torch.gt(A,C))

tensor([False, False, False, False, False, False])
tensor([[False, False, False, False, False, False]])


In [70]:
# 逐元素比较小于等于
print(torch.le(A,B))
print(torch.lt(A,C))

tensor([True, True, True, True, True, True])
tensor([[False, False, False, False, False, False]])


In [71]:
# 逐元素比较不等于
print(torch.ne(A,B))
print(torch.ne(A,C))

tensor([False, False, False, False, False, False])
tensor([[False, False, False, False, False, False]])


In [73]:
torch.isnan(torch.tensor([0,1,float('nan'),2]))

tensor([False, False,  True, False])

### 4.2 基本运算

In [74]:
## 矩阵逐元素相乘
A = torch.arange(6.0).reshape(2,3)
B = torch.linspace(10,20,steps=6).reshape(2,3)
print("A:", A)
print("B:", B)
print(A*B)
print(A/B)

A: tensor([[0., 1., 2.],
        [3., 4., 5.]])
B: tensor([[10., 12., 14.],
        [16., 18., 20.]])
tensor([[  0.,  12.,  28.],
        [ 48.,  72., 100.]])
tensor([[0.0000, 0.0833, 0.1429],
        [0.1875, 0.2222, 0.2500]])


In [ ]:
print(A+B)# 逐元素加
print(A-B) # 逐元素减
print(B//A) # 逐元素整除

tensor([[10., 13., 16.],
        [19., 22., 25.]])
tensor([[-10., -11., -12.],
        [-13., -14., -15.]])
tensor([[inf, 12.,  7.],
        [ 5.,  4.,  4.]])


In [76]:
print(torch.pow(A, 3))
print(A ** 3)

tensor([[  0.,   1.,   8.],
        [ 27.,  64., 125.]])
tensor([[  0.,   1.,   8.],
        [ 27.,  64., 125.]])


In [ ]:
print(A)
# 张量的指数
torch.exp(A)
# e0.0=1.0
# e1.0≈2.71828
# e2.0≈7.38906
# e3.0≈20.08554
# e4.0≈54.59815
# e5.0≈148.41316

tensor([[0., 1., 2.],
        [3., 4., 5.]])


tensor([[  1.0000,   2.7183,   7.3891],
        [ 20.0855,  54.5982, 148.4132]])

In [ ]:
# 张量的对数
torch.log(A)

tensor([[  -inf, 0.0000, 0.6931],
        [1.0986, 1.3863, 1.6094]])

In [81]:
# 张量的平方根
print(torch.sqrt(A))
print(A ** 0.5)

tensor([[0.0000, 1.0000, 1.4142],
        [1.7321, 2.0000, 2.2361]])
tensor([[0.0000, 1.0000, 1.4142],
        [1.7321, 2.0000, 2.2361]])


In [82]:
# 张量的平方根倒数
print(torch.rsqrt(A))
print(1 / (A ** 0.5))

tensor([[   inf, 1.0000, 0.7071],
        [0.5774, 0.5000, 0.4472]])
tensor([[   inf, 1.0000, 0.7071],
        [0.5774, 0.5000, 0.4472]])


In [83]:
## 张量的数据剪裁
torch.clamp_max(A, 4)

tensor([[0., 1., 2.],
        [3., 4., 4.]])

In [84]:
## 张量的数据剪裁
torch.clamp_min(A,3)

tensor([[3., 3., 3.],
        [3., 4., 5.]])

In [ ]:
## 张量的数据剪裁
torch.clamp(A, 2.5, 4)

tensor([[2.5000, 2.5000, 2.5000],
        [3.0000, 4.0000, 4.0000]])

In [86]:
print(A)
## 矩阵的转置
C = torch.t(A)
C

tensor([[0., 1., 2.],
        [3., 4., 5.]])


tensor([[0., 3.],
        [1., 4.],
        [2., 5.]])

In [87]:
## 矩阵云散，矩阵相乘， A的行数要等于C的列数
A.matmul(C)

tensor([[ 5., 14.],
        [14., 50.]])

In [88]:
A = torch.arange(12.0).reshape(2,2,3)
B = torch.arange(12.0).reshape(2,3,2)
AB = torch.matmul(A,B)
AB

tensor([[[ 10.,  13.],
         [ 28.,  40.]],

        [[172., 193.],
         [244., 274.]]])

In [89]:
## 矩阵相乘之计算最后面的两个维度的乘法
print(AB[0].eq(torch.matmul(A[0], B[0])))
print(AB[1].eq(torch.matmul(A[1], B[1])))

tensor([[True, True],
        [True, True]])
tensor([[True, True],
        [True, True]])


In [92]:
## 矩阵的逆
C = torch.rand(3,3)
print(C)
D = torch.inverse(C)
print(D)
torch.mm(C,D)

tensor([[0.5276, 0.7621, 0.4403],
        [0.3083, 0.1194, 0.8924],
        [0.7664, 0.1085, 0.7034]])
tensor([[-0.0395, -1.5086,  1.9388],
        [ 1.4433,  0.1040, -1.0354],
        [-0.1795,  1.6277, -0.5311]])


tensor([[1.0000e+00, 3.5760e-08, 6.1513e-08],
        [7.4419e-09, 1.0000e+00, 6.1006e-09],
        [1.4901e-08, 0.0000e+00, 1.0000e+00]])

In [95]:
## 计算张量矩阵的迹，对角线元素的和
torch.trace(torch.arange(9.0).reshape(3,3))

tensor(12.)

### 4.3 统计相关的计算